apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Ops Project
  sourceRepos:
  - 'https://github.com/kaguptas/argo-test'
  - 'https://grafana.github.io/helm-charts'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: '*'
    server: dev-kgupta-worker
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
